[build]
  functions = "netlify/functions"   # Path where your serverless functions are located
  publish = "dist"                   # Where your static files (if any) are published
  command = "npm run build"          # Command to build your project (you can change this if needed)

[[plugins]]
  package = "@netlify/plugin-functions-core"  # Ensures your functions work correctly
